### ISSUE TITLE
High-Level Route Selection

### ISSUE THREAD

**Issue by barulicm** [RoboJackets/roboracing-software#65]
Implement a high-level planner which picks which route we will take through the course. Should be able to answer questions from the path-planner when multiple paths are detected.

**Comment by btdubs** [comment]
As a goal for IARRC 2019, I'd like to say being able to detect the cones at the iarrc intersection and being able to publish something about telling us they are there and to turn into it, otherwise telling us to continue on our normal (straight) best path.

Later this can look like seeing the barrels or ramp at AVC and giving us pre-written instructions to turn into or away from some obstacles.

**Comment by Daniel-Martin576** [comment]
Closed due to canceled competition.
